### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Keller18306** [PassTheMayo/minecraft-server-util#21]
[
![CvWqWAp0Mgs](https://user-images.githubusercontent.com/23178771/96009557-74ce2300-0e49-11eb-98f2-ff0ed94b4e46.jpg)
](url)

**Comment by PassTheMayo** [comment]
This isn't an error with the library, it's an issue with your network. I've had issues like this before, the only solution was to switch network providers or hosting companies.

**Comment by PassTheMayo** [comment]
I'll continue to look into this issue, though. I'll see if there's anything I can do on my end.
