### ISSUE TITLE
[Bug] Run Callback Returning undefined

### ISSUE THREAD

**Issue by Elveskevtar** [PassTheMayo/minecraft-server-util#22]
Minified Example:
```
const util = require('minecraft-server-util');
const client = new util.RCON('server.com', { port: 25575, password: 'blahblah' });
client.on('output', (message) => console.log(message));
client.connect()
    .then(async () => {
        await client.run('list');
        client.close();
    })
    .catch((error) => {
        console.log(error);
    });
```
Server Specs:
Minecraft Forge Server 1.16.3
Running on EC2 instance with ports 25565 and 25575 open for inbound traffic both TCP/UDP.

The output event callback is never triggered. I can tell that the RCON commands are reaching the server because I get `Thread RCON Client /<IP> started` in the server logs. Also, if I replace 'list' with 'stop' it will shut down the server.

If I try to console log the result of the run call, it is undefined.

I'll try to discover the root cause in the meantime.

**Comment by Elveskevtar** [comment]
I've unblocked myself as I can see that queryFull can actually print the players on the server, but I am still curious as to this issue.

**Comment by PassTheMayo** [comment]
I've discovered an issue with how the client will indefinitely loop and never process the packet. Try updating to `3.0.4` and re-verify that the issue exists. I've done some testing on my end and it seems to be working fine.
