### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by DEVTomatoCake** [PassTheMayo/minecraft-server-util#23]
Please add more examples to the wiki how to get the status of a server with giving a port, because when I use the port in the host there is an error...

Error: getaddrinfo ENOTFOUND IP:Port
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'IP:Port'
}

Using the latest npm version, on an older version (1.1.1) it works

**Comment by PassTheMayo** [comment]
There is already an example on the README that shows how to specify a port.

**Comment by DEVTomatoCake** [comment]
okay sorry, but then please update the wiki pages...

**Comment by PassTheMayo** [comment]
There is nothing wrong with the models on the wiki pages. The `StatusOptions` extends the `BaseOptions` model, just like it says: `StatusOptions extends BaseOptions`.
