### ISSUE TITLE
modInfo is always null

### ISSUE THREAD

**Issue by T1MOXA** [PassTheMayo/minecraft-server-util#24]
Tested with different library.
```js
const util = require("minecraft-server-util");
const mcping = require("mcping-js");

const host = 'localhost';
const port = 25565;

util.status(host, { port }).then((response) => {
    console.log("minecraft-server-util", response);
}).catch((error) => {
    console.error("minecraft-server-util", error);
});

const server = new mcping.MinecraftServer(host, port);

server.ping(10e3, 753, (err, res) => {
    if (err) console.error("mcping-js", err);
	console.log("mcping-js", res);
});
```

**Comment by PassTheMayo** [comment]
Do you have any more data to back this up? I've done some testing and it appears to be working just fine. What version of the library are you using?

![image](https://user-images.githubusercontent.com/16949253/98182457-6bc1f600-1ecb-11eb-9c42-e16d7d688eb7.png)

**Comment by rbestardpino** [comment]
Hi! I am facing the same error as @T1MOXA . I will provide more context tho.

Here it is my file, straight and simple code from the wiki:

```js
const util = require("minecraft-server-util");

util
  .status("mc.rbestardpino.xyz")
  .then((response) => {
    console.log(response.modInfo);
  })
  .catch((error) => {
    throw error;
  });
```

The output is just `null`, you can try it with the same server if you want, it will be online. The modpack that I am currently using is ATM6.

"Live" example:
![image](https://user-images.githubusercontent.com/49445152/111052235-0f05b780-8438-11eb-9c49-a23b656a2e6c.png)


I truly don't mind at all, I don't need the mod info. Also, if needed, I can get the mod info by using another APIs (like https://api.mcsrvstat.us/2/mc.rbestardpino.xyz). So I am just providing more data than the opener of this issue.

**Comment by PassTheMayo** [comment]
I am going to be using this issue to track progress on getting `modInfo` back onto the response in version 5. I will close this again once this has been implemented.
