### ISSUE TITLE
Cannot get information from server which have use port 19132

### ISSUE THREAD

**Issue by sinhpn92** [PassTheMayo/minecraft-server-util#25]
Hi team,
I did try to use this lib to fetch server infor of `bw.lbsg.net:19132`. But I have got error this server not online.
What's wrong here?

**Comment by PassTheMayo** [comment]
Can you provide your code so I can see what is wrong?

**Comment by sinhpn92** [comment]
I have implemented with the same of your example. Maybe this lib do not support PocketMine :(

**Comment by PassTheMayo** [comment]
I haven't tested this with PocketMine yet. I was wondering what your code was because you mentioned that you used `bw.lbsg.net:19132` but this library does not support including the port within the host string.
