### ISSUE TITLE
bug: webpack error

### ISSUE THREAD

**Issue by wrw1997** [PassTheMayo/minecraft-server-util#29]
**Describe the bug:**
while I was running a dev server via vue-cli, it shows me errors like this:
[I just wrote like the example of 'util.status()', and npm console said that I need to install 'dns' dependency. I did it and install 'net' as well.]
![image](https://user-images.githubusercontent.com/35623575/102017793-fa1b7880-3da3-11eb-842f-78aac5ce0a0a.png)

**Comment by PassTheMayo** [comment]
This module can't be used in Webpack because the browser environment doesn't support TCP or UDP sockets which is required in order to send and receive information from Minecraft servers, that's why it's missing the `net` module, and then the `dgram` module too.
