### ISSUE TITLE
bug: Hang calling statusBedrock with unreachable server

### ISSUE THREAD

**Issue by potomato** [PassTheMayo/minecraft-server-util#31]
**Describe the bug:**
Calling statusBedrock against a host that does not respond appears to cause a hang waiting for a promise to resolve. 
Using the code below as the only code in a node script works successfully when targeting an online host/port combination. I see all the expected output and then the node process exits.
Changing to an IP address where there is no server and running the same code results in:
```
statusBedrock returned
Promise rejected
Failed to retrieve the status of the server within time
```
but then node never exits.

**Code:**
```javascript
mcsutil.statusBedrock(server, {port:19132, timeout: 2000})
    .then((response) => {
        console.log("Promise resolved");
        console.log(response);
    })
    .catch((error) => {
        console.log("Promise rejected");
        console.log(error);
    });
console.log("statusBedrock returned");
```

**Expected behavior:**
When a bedrock server is unavailable the code above should exit cleanly on completion.

**Additional context**
The issue may be similar to https://github.com/PassTheMayo/minecraft-server-util/issues/27
I have tried to repro a simple case by simulating readPacket never resolving (as that was my suspicion) but cannot get into the same situation.

**Comment by PassTheMayo** [comment]
I was able to reproduce this issue on the most recent commit. I've determined that the source of the issue is that the UDP socket that is created never gets destroyed when there is an error located elsewhere. This was simply fixed by `socket.unref()` in the UDP socket class. I've published `3.4.3` just now which has fixed this issue. Let me know if you have any more problems.

**Comment by potomato** [comment]
Many thanks @PassTheMayo for your amazing response! Just tried it now and all looks good. Really appreciate having one package that happily queries both java and bedrock editions.

**Comment by PassTheMayo** [comment]
No problem! Glad my package suits your needs.
