### ISSUE TITLE
Error "Do not know how to serialize a BigInt"

### ISSUE THREAD

**Issue by MatsG23** [PassTheMayo/minecraft-server-util#40]
Hello!

When I try getting the status of a Bedrock server it always fails with the error "Do not know how to serialize a BigInt".

I'm awaiting the async function and it works perfectly for the Java minecraft server but not for Bedrock.
The server is running on PaperMC and the Bedrock server is powered by GeyserMC (a proxy to make a Bedrock server like the Java server). I can connect to the Bedrock server on the phone so I can verify it should work.

Best Regards
Mats

**Comment by Synthetic-Dev** [comment]
Please provide an example of your code, does it error on the request line (status/query) or does it error on a line within your .then statement?
This is probably the most likely cause of your error.
![image](https://user-images.githubusercontent.com/35655841/118357031-d9806600-b56f-11eb-8c2a-f2fe5acb42b2.png)

**Comment by PassTheMayo** [comment]
Synthetic-Dev is right here. You are trying to use `JSON.stringify()` on the response object which cannot work. The response object contains a `BigInt` value which is not serializable. If you can provide your code, we can help you solve this.

**Comment by MatsG23** [comment]
I think it indeed was my stupidity! I retried in a fresh project and now it works as expected.
