### ISSUE TITLE
bug: MOTD duplicating text

### ISSUE THREAD

**Issue by KazakEz** [PassTheMayo/minecraft-server-util#57]
**Describe the bug:**
Return MOTD with errors

**Code:**
```javascript
util.status(args[0], { port: parseInt(args[1]) }).then((response) => {
   const MOTD = response.motd.raw.replace(/§\S/g, '');
}
```

![image](https://user-images.githubusercontent.com/70358000/142262960-c5a345d1-69dc-4149-955b-92844a251c73.png)
![image](https://user-images.githubusercontent.com/70358000/142262992-17f10325-cf37-4a6d-a133-87881b8f17e2.png)

Previously, before updating the library, it worked as it should, but now for some reason it started to duplicate messages. I apologize if there are any mistakes in my text. I am not English and I translate through a translator, but he can make mistakes

**Comment by PassTheMayo** [comment]
I haven't been able to reproduce the bug with any of my test servers. Can you send the IP address of the server you tested so I can reproduce this exact issue?

**Comment by KazakEz** [comment]
Yes, servers with bug:
vimeworld.net
mc.ds-join.ru
go.migosmc.ru

**Comment by KazakEz** [comment]
repeated?

**Comment by KazakEz** [comment]
@PassTheMayo wake up

**Comment by PassTheMayo** [comment]
@KazakEz I did some testing with the IP addresses you provided and confirmed that there doesn't appear to be any duplication issues with the MOTD. I just released version `5.0.0` about an hour ago so you might update and try again.

![image](https://user-images.githubusercontent.com/16949253/143653984-fa85ec42-47a7-410f-9830-cd0cce72745f.png)

**Comment by KazakEz** [comment]
have new error
![изображение](https://user-images.githubusercontent.com/70358000/143773397-9f82ac69-335f-4623-ab9d-efb114a95eb8.png)

**Comment by PassTheMayo** [comment]
@KazakEz That is because `5.0.0` is a major change update, your old code is not going to work. Look at the examples on the README.

**Comment by KazakEz** [comment]
> @KazakEz That is because `5.0.0` is a major change update, your old code is not going to work. Look at the examples on the README.

![изображение](https://user-images.githubusercontent.com/70358000/143784744-dd5df3b3-d95f-49d5-b57a-b3b5a04b3a15.png)
5.0.2

**Comment by PassTheMayo** [comment]
According to the code you provided, you are still using the old argument style of `status()` which is incompatible with this major release. You can view the new examples on the README: [https://github.com/PassTheMayo/minecraft-server-util#get-the-status-of-a-java-server-with-options](https://github.com/PassTheMayo/minecraft-server-util#get-the-status-of-a-java-server-with-options). You are providing the options object in place of where the port should be, which is why you are receiving this error.

**Comment by KazakEz** [comment]
> According to the code you provided, you are still using the old argument style of `status()` which is incompatible with this major release. You can view the new examples on the README: https://github.com/PassTheMayo/minecraft-server-util#get-the-status-of-a-java-server-with-options. You are providing the options object in place of where the port should be, which is why you are receiving this error.

check
![изображение](https://user-images.githubusercontent.com/70358000/144157565-82ebc4b2-d8a5-4088-955e-7caa5da08024.png)
![изображение](https://user-images.githubusercontent.com/70358000/144157587-3c0a1629-9ac5-47b6-87af-1f8b5057fbb9.png)
![изображение](https://user-images.githubusercontent.com/70358000/144157609-5b14f58d-1f8a-41db-9851-d9c321187781.png)

**Comment by KazakEz** [comment]
### fixed 
(UPD node.js to v16 and all working)
