### ISSUE TITLE
bug: hanging statusBedrock()

### ISSUE THREAD

**Issue by NovaLynxie** [PassTheMayo/minecraft-server-util#59]
**Describe the bug:**
When pinging any 'Bedrock' server with the method statusBedrock() it never returns a response and just hangs endlessly.
I have tried with several working bedrock server IPs and none of them ever returned an error or complete the request.
One such server I tried to ping to test this is play.magmamc.net:19132 (I have checked that this is indeed a bedrock server)
**Code:**
```javascript
const logger = require('../../utils/winstonLogger');
const mcu = require('minecraft-server-util');
const { SlashCommandBuilder } = require('@discordjs/builders');
const { MessageAttachment, MessageEmbed } = require('discord.js');
const { stripIndents } = require('common-tags');

module.exports = {
	data: new SlashCommandBuilder()
		.setName('mc')
		.setDescription('Pings specified server IP and address.')
    .addStringOption(option =>
      option
        .setName('type')
        .setDescription('Java or Bedrock')
        .setRequired(true)
        .addChoice('Java','java')
        .addChoice('Bedrock','bedrock')
    )
    .addStringOption(option =>
      option
        .setName('host')
        .setDescription('Host IP')
        .setRequired(true)
    )
    .addIntegerOption(option =>
      option
        .setName('port')
        .setDescription('Port')
        .setRequired(false)
    ),
	async execute(interaction, client) {
    await interaction.deferReply();
    const options = interaction.options;
    const type = options.getString('type');
    const host = options.getString('host');
    const port = options.getInteger('port');
    let mcEmbed = new MessageEmbed(), mcOptions = { timeout: 30000, enableSRV: true },  mcServerData;
    if (host.toLowerCase() === 'localhost') return interaction.editReply({ content: "Please don't ping my mainframe. Any `localhost` request is disallowed and will simply be refused."});
    const slowServerResponse = setTimeout(() => {
      logger.debug('Response taking longer than 15s. Is the server lagging or slow connection?')
      interaction.editReply({
        content: 'It looks like the server is taking a very long to respond. If the requested server is running slower than normal, it could be experiencing lag issues due to low TPS.'
    })}, 15000);
    try {
      if (type === 'java') {
        logger.debug(`Pinging MC_JAVA_SERVER at ${host}:${port||25565}.`);
        mcServerData = await mcu.status(host, port || 25565, mcOptions);
        logger.debug(`Got a response from ${host}:${port||25565}!`);
      };
      if (type === 'bedrock') {
        logger.debug(`Pinging MC_BEDROCK_SERVER at ${host}:${port||19132}.`);
        mcServerData = await mcu.statusBedrock(host, port || 19132, mcOptions); // <-- code just hangs here awaiting a response.
        logger.debug(`Got a response from ${host}:${port||19132}!`);
      };
      const { description, motd, players, version, favicon, roundTripLatency } = mcServerData;
    //... (all code past this point is just embed formatting before sending to a Discord server's channel)
  },
};
```

**Expected behavior:**
The line 'code hangs here' should either error out if it cannot connect to the server or return a response and store the data in 'mcServerData' ready to be used elsewhere.

**Additional context**
I have checked the server IPs mentioned from a minecraft voting site and they do report the server is online and responding.
Used to use v3.6.0 (forgot to update it) of the minecraft-server-util module which did in some cases actually return an error or a valid response.
Edit: Left the code running for a few minutes while debugging and it still has not resolved with data or rejected with an error.
Forgot to mention the code above is from my Discord bot which runs NodeJS v16 and is hosted via replit.com.

**Comment by NovaLynxie** [comment]
The version of minecraft-server-util I am using currently is v5.1.1. I have tried testing using a simple test code which also produces the same hanging problem.
```javascript
const mcu = require('minecraft-server-util');

mcu.statusBedrock('play.magmamc.net', 19132, { enableSRV: true })
  .then((response) => {
    console.log("Promise resolved [BEDROCK]");
    console.log(response);
  })
  .catch((error) => {
    console.log("Promise rejected [BEDROCK]");
    console.log(error);
  });
console.log("BedrockEdition request started");
```
Though I'm beginning to wonder if the response is not being received properly with the code environment I have been using as I have also observed the same issue when running queryBasic() and queryFull() methods as well, they don't return any response and hang the same as statusBedrock(). 
All my code has been run inside a bash 'repl' running NodeJS v16 hosted via replit.com.
I'll try running a local version of my code and see if that receives the response properly.

**Comment by Ndrs24** [comment]
I have the same problem and testing I have realized that since v5.0.0 statusBedrock() does not return a result

**Comment by PassTheMayo** [comment]
I've narrowed this down to be a networking issue on the client end. Repl.it doesn't allow UDP connections, and my guess is that your local network isn't allowing them either. I've been able to retrieve the status of that server on multiple networks that allow UDP, but haven't been able to on Repl.it because of them blocking UDP.

**Comment by NovaLynxie** [comment]
Yep, that would be it. I just did a quick test and the local network is allowing it properly.
Suspected the same as you @PassTheMayo that UDP packets aren't working on repl.it. 
Did some research into that after opening the issue, sorry about that.
Looks like I'll need to use another way for my repl.it hosted instance...
Thanks anyway, still love using this module whenever possible.
