### ISSUE TITLE
bug: undefined at the end of MOTD in statusBedrock response.

### ISSUE THREAD

**Issue by mve** [PassTheMayo/minecraft-server-util#68]
**Describe the bug:**
Some bedrock servers, for example: play.lbsg.net might not have a second line of motd. This causes undefined to be added to the motd string. 

``` "clean": "EU> Adopt-A-Pet Beta\nundefined" ```

It seems to me like it's caused by this piece of code:
Line 76 in statusBedrock.ts
```javascript
const motd = parse(motdLine1 + '\n' + motdLine2);
```
motdLine2 might be undefined.

**Expected behavior:**
Check if motdLine2 is undefined, if so, don't add it to the MOTD string.

**Comment by PassTheMayo** [comment]
I just went ahead and fixed this issue within version `5.2.8` on npm along with the other issue that you opened earlier. Let me know if this has been fixed on your end.
