### ISSUE TITLE
bug: port only recognized as an object not as a number

### ISSUE THREAD

**Issue by Baggette** [PassTheMayo/minecraft-server-util#72]
**Describe the bug:**
the code doesn't want to recognize the port as a number. ```AssertionError [ERR_ASSERTION]: Expected 'port' to be a 'number', got 'object'``` I have tried ```{port: `${args[1]}`}```, ```{port: Number(args[1])}``` and ```{port: parseInt(args[1])}```. I console logged args[0] and args[1] it does register the ip and port correctly it just doesn't want to use the port as a number. 

**Code:**
```javascript
const util = require('minecraft-server-util');

module.exports = {
    name: 'mcping',
    description: 'get information about a minecraft server',
    execute(client, message, args, Discord){
        if(!args[0]) return message.channel.send('Please enter a minecraft server ip');
        if(!args[1]) return message.channel.send('Please enter a minecraft server port');

        util.status(args[0], {port: parseInt(args[1])}).then((response) =>{
            console.log(response);
            const embed = new Discord.MessageEmbed()
            .setColor('#BFCDEB')
            .setTitle('Mc server status')
            .addFields(
                {name: 'Server IP', value: response.host},
                {name: 'Online Players', value: response.onlinePlayers},
                {name: 'Max Players', value: response.maxPlayers},
                {name: 'Version', value: response.version}
            )
            .setFooter('Mc server util by Baggette');

            message.channel.send(embed);
        })
        .catch ((error) =>{
            message.channel.send('there was an error finding this server');
            throw error;
        })
    }
}
```

**Expected behavior:**
bot replies with server information. I wanted the command to work like gmcping serverip port. 

**Additional context**
Its not being hosted on replit. 
I am somewhat new to javascript so maybe im just doing something wrong.

**Comment by PassTheMayo** [comment]
The reason you are getting this error is because you updated the library without changing your code. Look at the examples on the wiki. The port argument is now the second argument and the options is the third argument.
