### ISSUE TITLE
`timeout` option for Query

### ISSUE THREAD

**Issue by Cursor-S** [PassTheMayo/minecraft-server-util#76]
I've noticed that there isn't a timeout option for `util.queryBasic()` or `util.queryFull()`.

the default value seems to be 5000 in milliseconds, but I actually hope for an option like that can enable me to change the timeout value.

Thanks.

**Comment by MangoSwirl** [comment]
This is already implemented. Try setting `options.timeout`.

Example:
```js
const options = {
    sessionID: 1,
    enableSRV: true,
    timeout: 3000 // Optional, defaults to 5000 ms
};

util.queryBasic('localhost', 25565, options)
    .then((result) => console.log(result))
    .catch((error) => console.error(error));
```

It seems to be missing from the documentation, which should be fixed.
