### ISSUE TITLE
bug: Issue with a server that does not send player counts or samples

### ISSUE THREAD

**Issue by AMDBartek** [PassTheMayo/minecraft-server-util#83]
**Describe the bug:**
Library is incompatible with a server that does not send player count or sample.

**Code:**
```
const mcUtil = require("minecraft-server-util");

const mcUtilOptions = {
    timeout: 7500,
    enableSRV: true
};

mcUtil.status("removed IP", portnumber, mcUtilOptions).then(
   (result) => console.log(result)
).catch(
(error) => console.log(error)
);
```

**Error:**
```
TypeError: Cannot read properties of undefined (reading 'online')
    at Object.<anonymous> (/home/bartek/Desktop/terracraft.js/node_modules/minecraft-server-util/dist/status.js:112:46)
    at Generator.next (<anonymous>)
    at fulfilled (/home/bartek/Desktop/terracraft.js/node_modules/minecraft-server-util/dist/status.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Expected behavior:**
The server to return the status successfully but without player count or sample information.

**Additional context**
My private server does not send any player count or sample information. This seems to upset the library.
![image](https://user-images.githubusercontent.com/46637209/226765566-8102f789-617c-4883-b14d-e465ecfe54ae.png)

**Comment by PassTheMayo** [comment]
Thank you for bringing this issue to my attention. I did not realize that Minecraft allows you to not send a player count. I’ll likely be implementing a fix tomorrow night in this library as well as my Go library for retrieving Minecraft statuses.

**Comment by PassTheMayo** [comment]
Apologies for a late reply, but unfortunately I will not be fixing this issue on this library, as the library will be deprecated soon due to issues with reliability with the standard networking library in Node.js. I've posted more information about this on the README.

**Comment by AMDBartek** [comment]
All good, I will maintain my own version of the library.
